---
- name: "Create Backup User"
  become: yes
  ansible.builtin.user:
    name: "borgbackup"
    generate_ssh_key: yes
    ssh_key_type: ed25519
    state: present
    groups: "{{ borg_user_groups }}"
  register: borgbackup_user

- name: Display Borg User
  ansible.builtin.debug:
    msg: "{{ borgbackup_user['ssh_public_key'] }}"

- name: Wait for Repo Auth confirmation.
  when: borgbackup_user.changed
  ansible.builtin.pause:
    prompt: "Make sure Pubkey is in the Repos authorized keys list"
